PorfolioApp/Controllers/ExperienceController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Core_Project.Controllers
{
    public class ExperienceController : Controller
    {
        ExperienceManager experienceManager = new ExperienceManager(new EfExperienceDal());
        public IActionResult Index()
        {
            ViewBag.V1 = "Deneyim Listesi";
            ViewBag.V2 = "Deneyimler";
            ViewBag.V3 = "Deneyim Listesi";
            var values = experienceManager.GetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult ExperienceAdd()
        {
            return View();
        }
        [HttpPost]
        public IActionResult ExperienceAdd(Experience experience)
        {
            experienceManager.TAdd(experience);
            return RedirectToAction("Index");
        }

        public IActionResult ExperienceDelete(int id)
        {
            var values = experienceManager.GetByID(id);
            experienceManager.TDelete(values);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult ExperienceEdit(int id)
        {
            ViewBag.V1 = "Deneyim Listesi";
            ViewBag.V2 = "Deneyimler";
            ViewBag.V3 = "Deneyim Listesi";
            var values = experienceManager.GetByID(id);
            return View(values);
        }

        [HttpPost]
        public IActionResult ExperienceEdit(Experience experience)
        {
            experienceManager.TUpdate(experience);
            return RedirectToAction("Index");
        }

    }
}

PorfolioApp/Views/Experience/ExperienceAdd.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "ExperienceAdd";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Deneyim Ekleme Sayfası</h3>
</div>
@using (Html.BeginForm("ExperienceAdd", "Experience", FormMethod.Post))
{
    
    <br />
    @Html.Label("Deneyim  Başlığı")
    @Html.TextBoxFor(x=>x.Name,new{ @class="form-control"})
    <br />
    <label>Tarih Bilgisi</label>
    @Html.TextBoxFor(x=>x.Date,new { @class ="form-control"})
    <br />
    <label>Resim Yolu</label>
    @Html.TextBoxFor(x=>x.ImageUrl,new { @class ="form-control"})
    <br />
    <label>Şirket İsmi</label>
    @Html.TextAreaFor(x=>x.CompanyName,10,3,new { @class ="form-control"})
    <br />
    <label>Açıklama</label>
    @Html.TextAreaFor(x=>x.Description,10,3,new { @class ="form-control"})
    <br />
    <button class="btn btn-primary">Ekle</button>
}

PorfolioApp/Views/Experience/ExperienceEdit.cshtml
@model EntityLayer.Concrete.Experience
@{
    ViewData["Title"] = "ExperienceEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Deneyim Düzenleme Sayfası</h3>
</div>
@using (Html.BeginForm("ExperienceEdit", "Experience", FormMethod.Post))
{
    @Html.HiddenFor(x=>x.ExperienceID)
        <br />
    @Html.Label("Deneyim  Başlığı")
    @Html.TextBoxFor(x=>x.Name,new{ @class="form-control"})
        <br />
        <label>Tarih Bilgisi</label>
    @Html.TextBoxFor(x=>x.Date,new { @class ="form-control"})
        <br />
        <label>Resim Yolu</label>
    @Html.TextBoxFor(x=>x.ImageUrl,new { @class ="form-control"})
        <br />
        <label>Şirket İsmi</label>
    @Html.TextBoxFor(x=>x.CompanyName,new { @class ="form-control"})
    <br />
    <label>Açıklama</label>
    @Html.TextAreaFor(x=>x.Description,10,3,new { @class ="form-control"})
        <br />
        <button class="btn btn-primary">Düzenle</button>
}

PorfolioApp/Views/Experience/Index.cshtml
@using EntityLayer.Concrete
@model List<Experience>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


<!-- Light table -->
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Deneyim Listesi</h4>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Başlık</th>
                            <th>Tarih</th>
                            <th>Sil</th>
                            <th>Güncelle</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var item in Model)
                        {
                            <tr>
                                <td>@item.ExperienceID</td>
                                <td>@item.Name</td>
                                <td>@item.Date</td>
                                <td><a href="#" class="btn btn-outline-danger">Sil</a></td>
                                <td><a href="#" class="btn btn-outline-success">Güncelle</a></td>
                               
                                
                            </tr>
                        }
                        
            
                    </tbody>
                </table>
                <a href="/Experience/ExperienceAdd" class="btn btn-outline-success">Yeni Deneyim Ekle</a>
            </div>
        </div>
    </div>
</div>